name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc: [ghc96, ghc98, ghc910, ghc912]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Set up Cachix
        uses: cachix/cachix-action@v16
        with:
          name: awakesecurity
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix build --print-build-logs .#with-${{ matrix.ghc }}
